const ONE_MINUTE = 60 * 1000;
const ONE_HOUR = 60 * ONE_MINUTE;
const TWO_MINUTES = 2 * ONE_MINUTE;
const TEN_MINUTES = 10 * ONE_MINUTE;

export const INTERVALS = [ TWO_MINUTES, TEN_MINUTES, ONE_HOUR ];